const data = {
  products: [
    {
      _id: '1',
      name: 'Chemise femme',
      slug: 'Chemise femme',
      category: 'T-shirt',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 100,
      brand: '123',
      rating: 4.5,
      numReviews: 20,
      description: 'Chemise beige de haute qualité',
    },

    {
      _id: '2',
      name: 'Jean',
      slug: 'Un Jean',
      category: 'Pantalons',
      image: '/images/p2.jpg',
      price: 50,
      countInStock: 0,
      brand: 'Mongo',
      rating: 4.0,
      numReviews: 10,
      description: 'Pantalon de haute qualité',
    },

    {
      _id: '3',
      name: 'Ensemble femme',
      slug: 'Ensemble femme',
      category: 'T-shirt',
      image: '/images/p3.jpg',
      price: 90,
      countInStock: 150,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 14,
      description: 'Ensemble de haute qualité',
    },
    {
      _id: '4',
      name: 'Ensemble de sport pour femme',
      slug: 'Ensemble de sport pour femme',
      category: 'Pantalons',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 500,
      brand: 'Massimo dutti',
      rating: 4.5,
      numReviews: 10,
      description: 'Ensemble de haute qualité',
    },
  ],
};

export default data;
